export default {
    home: {
        ADD_MOVIE: 'ADD_MOVIE',
        SET_GENRE: 'SET_GENRE',
        SET_SORT_BY: 'SET_SORT_BY',
        SET_MOVIE_LIST: 'SET_MOVIE_LIST',
        SET_POPULAR_MOVIE: 'SET_POPULAR_MOVIE',
        SET_SELECTED_SORT: 'SET_SELECTED_SORT',
        SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
        SET_SELECTED_GENRE: 'SET_SELECTED_GENRE',
        SET_UPCOMING_MOVIE: 'SET_UPCOMING_MOVIE',
        SET_MOVIE_LIST_FILTER: 'SET_MOVIE_LIST_FILTER',
        SET_MOVIE_LIST_FILTER_SORT: 'SET_MOVIE_LIST_FILTER_SORT',
        REMOVE_MOVIE_LIST_FILTER: 'REMOVE_MOVIE_LIST_FILTER',
        REMOVE_MOVIE_LIST_FILTER_SORT: 'REMOVE_MOVIE_LIST_FILTER_SORT',
    },
    detail: {
        SET_MOVIE_DETAIL: 'SET_MOVIE_DETAIL',
        SET_MOVIE_REVIEWS: 'SET_MOVIE_REVIEWS',
        SET_MOVIE_RECOMENDATION: 'SET_MOVIE_RECOMENDATION'
    }
}